---
- hosts: localhost

  vars_files:
    - 'defaults/main.yml'

  tasks:

    - name: Overwrite vars from defaults
      set_fact:
        # java_version: 8
        # java_subversion: 201
        java_download_path: /tmp/java
        java_install_jce: true
        download_tar: true
        download_rpm: true
        download_dmg: true

    - name: Make sure download path exists
      file:
        path: "{{ java_download_path }}"
        state: directory

    ##############
    ### tar.gz ###
    ##############

    - block:
        - name: Set os and architecture
          set_fact:
            jdk_os: linux
            jdk_arch: x64
            use_dmg: false
            use_rpm: false
            use_tarball: true
            install_file_extension: tar.gz
            jdk_file_name: false

        - name: Set jdk variables
          import_tasks: tasks/set-jdk-vars.yml

        - name: Download from Oracle
          import_tasks: tasks/fetch.yml

      when: download_tar

    ##############
    ### rpm    ###
    ##############

    - block:
        - name: Set os and architecture
          set_fact:
            jdk_os: linux
            jdk_arch: x64
            use_dmg: false
            use_rpm: true
            use_tarball: false
            install_file_extension: rpm
            jdk_file_name: false

        - name: Set jdk variables
          import_tasks: tasks/set-jdk-vars.yml

        - name: Download from Oracle
          import_tasks: tasks/fetch.yml

      when: download_rpm

    ##############
    ### dmg    ###
    ##############

    - block:
        - name: Set OS
          set_fact:
            jdk_os: macosx
          when: java_version == 8

        - name: Set OS
          set_fact:
            jdk_os: osx
          when: java_version > 8

        - name: Set file attributes
          set_fact:
            jdk_arch: x64
            use_dmg: true
            use_rpm: false
            use_tarball: false
            install_file_extension: dmg
            jdk_file_name: false

        - name: Set jdk variables
          import_tasks: tasks/set-jdk-vars.yml

        - name: Download from Oracle
          import_tasks: tasks/fetch.yml

      when: download_dmg

    ##############
    ### JCE    ###
    ##############

    - name: Fetch JCE files from Oracle site
      import_tasks: tasks/fetch_jce.yml
      when: java_install_jce
