---
- hosts: "{{ test_hosts|default('all') }}"
  become: true
  become_method: sudo
  tasks:
    - import_tasks: 'tasks/main.yml'

  # vars from defaults/main.yml
  vars:
    java_version: 9
    java_download_path: "{{ oracle_java.path }}"
    java_download_from: oracle
    java_mirror: "http://download.oracle.com/otn-pub/java/jdk"
    java_remove_download: false
    java_install_jce: false
    java_set_javahome: true
