---
- hosts: "{{ test_hosts|default('all') }}"
  become: true
  become_method: sudo
  tasks:
    - import_tasks: 'tasks/main.yml'

  # Variables from defaults/main.yml
  vars:
    - java_version: 10
    - java_download_path: "{{ oracle_java.path }}"
    - java_download_from: oracle
    - java_mirror: "http://download.oracle.com/otn-pub/java/jdk"
    - java_remove_download: false
    - java_set_java_home: true
