---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian9
    image: debian:9
    volumes:
      - /tmp/java:/tmp/java
    groups:
      - debian
provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: debian9_jdk8_with_var
verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
