---
- name: Converge
  hosts: all

  vars:
    - java_download_path: /tmp/java
    - java_remove_download: false
    - java_version: 8
    - java_subversion: 201
    - java_download_from: oracle
    - java_set_java_home: true

  roles:
    - role: ansible-oracle-java
