---
- name: Install app
  hosts: ab-logstash    
  become: yes 

  vars:
    - java_version: 8
    - java_subversion: 201
    - java_download_from: local 
    - logstash_conf: logstash/mylogstash.conf    
    - destination_logstash_folder: /etc/logstash/conf.d
    - elasticsearch_conf: elasticsearch/elasticsearch.yml    
    - destination_elasticsearch_folder: /etc/elasticsearch
    - monit_conf: logstash 
  
  roles:
    - role: srsp.oracle-java  
    - role: ntp
    - role: geerlingguy.elasticsearch   
    - role: geerlingguy.logstash
    - role: monit
  
  
  tasks:  

    - name: Copy logstash conf
      copy: src={{ logstash_conf }} dest={{ destination_logstash_folder }} 

    - name: Restart logstash
      shell: service logstash restart

    - name: Copy elasticsearch conf
      copy: src={{ elasticsearch_conf }} dest={{ destination_elasticsearch_folder }} 

    - name: Restart elasticsearch
      shell: service elasticsearch restart
  
    - name: Creating ini file
      ini_file:
        path: /etc/ini_file.txt
        section: general
        option: uniqueID  
        value: "{{ 1000 | random | to_uuid | upper }}" 


