---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: fedora29
    image: fedora:29
    volumes:
      - /tmp/java:/tmp/java
    groups:
      - fedora
provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: fedora29
verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
