---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu1810
    image: ubuntu:18.10
    volumes:
      - /tmp/java:/tmp/java
    groups:
      - ubuntu
provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: ubuntu1810
verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
