---
- name: Install app
  hosts: all    
  become: yes   
  remote_user: vagrant
   
  roles:
  - role: ping
  - role: apt-up
  - role: ntp
  - role: geerlingguy.haproxy
  - role: monit

  tasks: 
  - name: Creating ini file
    ini_file:
      path: /etc/ini_file.txt
      section: general
      option: uniqueID  
      value: "{{ 1000 | random | to_uuid | upper }}" 
             
  
  
   


