---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: opensuse15
    image: opensuse/leap:15.1
    volumes:
      - /tmp/java:/tmp/java
    groups:
      - suse
provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: opensuse15
verifier:
  name: testinfra
  directory: ../default/tests/
  lint:
    name: flake8
