---
# Install Oracle JDK 1.x on Mac OS X
#
# Reference: https://docs.oracle.com/javase/8/docs/technotes/guides/install/mac_jdk.html

- name: Set mount point
  set_fact:
    mountpoint: "/Volumes/JDK_{{ java_version }}.{{ java_subversion }}"

- name: Mount the downloaded dmg
  command: hdiutil attach -mountpoint {{ mountpoint }} "{{ java_download_path }}/{{ jdk_file_name }}.{{ install_file_extension }}"
  args:
    creates: "{{ mountpoint }}"

- name: Set volume name for JDK 12 and below
  set_fact:
    pkg_name: "{{ mountpoint }}/JDK {{ java_version }} Update {{ java_subversion }}.pkg"
  when: java_version < 13

- name: Set volume name for JDK 13 and up
  set_fact:
    pkg_name: "{{ mountpoint }}/JDK {{ java_version }}.{{ java_subversion }}.pkg"
  when: java_version > 12

- name: Install the pkg file from the dmg
  become: true
  become_method: sudo
  command: installer -pkg "{{ pkg_name }}" -target /
  when: (jdk_info.stdout|from_json).not_found

- name: Unmount the downloaded dmg
  command: hdiutil detach "{{ mountpoint }}"
  args:
    removes: "{{ mountpoint }}"
