version: '3.3'


services:

 balancer:
  image: nginx
  ports: 
  - 80:8080/tcp
  volumes: 
  - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
  depends_on:   
  - "web"   

 web:
  build: ./  
  links:
  - "mysql57:database"  
  volumes:
  - ./web/etc/sites-enabled:/etc/apache2/sites-enabled:rw
  - ./web/www:/var/www/site:rw



 mysql57:
  image: percona:5.7
  environment:
   MYSQL_ROOT_PASSWORD: 12345
  volumes:
  - ./mysql/configs/my.cnf:/etc/mysql/conf.d/custom.cnf:rw
  - ./mysql/mysql:/var/lib/mysql:rw
