Vagrant.configure("2") do |config|
  config.vm.define "source", autostart: false do |source|
	source.vm.box = "hashicorp/bionic64"
	config.ssh.insert_key = false
  end
  config.vm.define "output" do |output|
	output.vm.box = "packer_vagrant"
	output.vm.box_url = "file://package.box"
	config.ssh.insert_key = false
  end
  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "3024"]
   end
  
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 515, host: 515
config.vm.network "forwarded_port", guest: 10514, host: 10514
  config.vm.network "forwarded_port", guest: 22, host: 5022
  config.vm.synced_folder ".", "/vagrant", disabled: true
end